### ISSUE TITLE
Error in fit_aci_response documentation

### ISSUE THREAD

**Issue by Dom3442** [cdmuir/photosynthesis#16] opened 2024-02-15 10:40 UTC
Here https://cdmuir.github.io/photosynthesis/reference/fit_aci_response.html
The description for fit_aci_reponse states that "T_leaf is leaf temperature in Celsius," however in your example code you convert the temperature to Kelvin before calling the function.  When trying to run the code (using my data) it produces a out of bounds error if you don't convert the temperature to Kelvin.  Error is

"Error in summary(fitc)$coefficients[2, 2] : subscript out of bounds"

This makes me think that the function in fact needs to the temperature in Kelvin and the documentation stating that temperture is in Celsius is wrong.

**Comment by cdmuir** [comment] 2024-02-25 19:19
Thanks for your comment. The error you got have something to with indexing. Either 'summary(fitc)$coefficients' doesn't exist or it's not a two-dimensional array or one of the dimensions isn't length 2. I'm not sure without more information. It is not because of the leaf temperature units.

**Comment by Dom3442** [comment] 2024-02-26 13:19
Minimum code to reproduce error.  Taking your example code and deleting the conversion to Kelvin (since documentation says it wants temperature in Celsius).

```
library(photosynthesis)

data <- read.csv(system.file("extdata", "A_Ci_Q_data_1.csv",
                             package = "photosynthesis"
))

# Define a grouping factor based on light intensity to split the ACi
# curves
data$Q_2 <- as.factor((round(data$Qin, digits = 0)))

# Rename leaf temp variable without converting to Kelvin
data$T_leaf <- data$Tleaf

fit <- fit_aci_response(data[data$Q_2 == 1500, ],
                        varnames = list(
                          A_net = "A",
                          T_leaf = "T_leaf",
                          C_i = "Ci",
                          PPFD = "Qin"
                        )
)

```

I get the error message
"Error in summary(fitc)$coefficients[2, 2] : subscript out of bounds"

If I replace the conversion to Kelvin like following

```
library(photosynthesis)

data <- read.csv(system.file("extdata", "A_Ci_Q_data_1.csv",
                             package = "photosynthesis"
))

# Define a grouping factor based on light intensity to split the ACi
# curves
data$Q_2 <- as.factor((round(data$Qin, digits = 0)))

# Convert leaf temperature to K
data$T_leaf <- data$Tleaf+273.15

fit <- fit_aci_response(data[data$Q_2 == 1500, ],
                        varnames = list(
                          A_net = "A",
                          T_leaf = "T_leaf",
                          C_i = "Ci",
                          PPFD = "Qin"
                        )
)

```

Then no error is encountered.

**Comment by cdmuir** [comment] 2024-03-03 00:23
I understand now. The issue is with the documentation. I fixed in the most recent commit.

**Closed as completed by cdmuir** 2024-03-03 00:23 UTC
